apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.image.name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.image.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.image.name }}
    spec:
      imagePullSecrets:
        - name: acr-image-pull-secret
      containers:
        - name: {{ .Values.image.name }}
          image: {{ .Values.image.repository }}/{{ .Values.image.name }}:{{ default .Chart.AppVersion .Values.image.tag }}
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: {{ .Values.image.port }}
              protocol: TCP
          # env:
          # - name: env_1_name
          #   value: env_1_value