apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.image.name }}
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.image.port }}
      protocol: TCP
  selector:
    app: {{ .Values.image.name }}
